# Site settings
title: César Sepúlveda
description: |
  Director of Infrastructure SRE/DevSecOps

url: http://csepulveda.net

about_title: About
projects_title: Home

# User settings
user_description_appendix: |
  My personal blog writen using [gh-pages][gh-pages] and [jekyll][jekyll], based on [lrassaby's blog][lrassaby]

  [lrassaby]: https://github.com/lrassaby/lrassaby.github.io
  [gh-pages]: https://pages.github.com/
  [jekyll]: https://jekyllrb.com


# email: cesar.sepulveda.b@gmail.com
linkedin: csepulvedab
github: csepulveda
medium: csepulvedab

relevant_tags: ['kubernetes', 'go', 'race-cars']

author: César Sepúlveda
author_title: Infrastructure Engineer
author_photo: profile-photo.jpg
user_description_short: |
  I am a DevOps/SRE leader with over 13 years of experience, managing infrastructure and security to ensure scalability, reliability, and compliance.


# ## Disqus
# disqus_identifier: rassaby

# ## Tracker
google_analytics_id: G-YPBW8TZ5KS

keywords: 'software,engineer,devops,csepulveda'

## URLs
permalink: ':title/'

baseurl: ''
projects_url: '/'
about_url: '/about'


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


include: [_pages]
exclude: ['package.json', 'src' , 'node_modules', 'Gemfile', 'LICENSE', 'gulpfile.js', 'README.md']